spring:
  application:
    name: cart-consumer

  redis:
    host: 192.168.1.13
    port: 6379
    password:
    jedis:
      pool:
        max-active: 20

server:
  port: 7762

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
