spring:
  application:
    name: search-service
  data:
    solr:
      host: http://192.168.1.15:8983/solr/ik_core
  datasource:
    url: jdbc:mysql://localhost:3306/qf-v6?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=Asia/Shanghai
    username: root
    password: root
server:
    port: 8764

rabbitmq:
    host: 192.168.1.14
    port: 5672
    username: root
    password: root
    virtual-host: j1906
imageServer: http://192.168.1.16:8888

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

